openapi: 3.0.3
info:
  title: Admin API
  description: |-
    API para la gestión de usuarios, sectores e interrupciones de luz.
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: admin
    description: Operaciones sobre clientes/usuarios
  - name: sector
    description: Operaciones sobre sectores
  - name: interruption
    description: Operaciones sobre interrupciones
  - name: client
    description: Operaciones de cliente
paths:
  /dashboard:
    get:
      tags:
        - admin
      summary: Obtener el dashboard de administración
      description: Obtiene información general del dashboard
      operationId: getDashboard
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Dashboard de administración cargado
        "401":
          description: No autorizado
        "403":
          description: Acceso denegado

  /:
    post:
      tags:
        - admin
      summary: Crear un nuevo usuario
      description: Crear un usuario en el sistema
      operationId: createUser
      requestBody:
        description: Datos del usuario a crear
        content:
          application/json:
            schema:
              type: object
              properties:
                idCard:
                  type: string
                name:
                  type: string
                email:
                  type: string
              required:
                - idCard
                - name
                - email
      responses:
        "201":
          description: Usuario creado
        "400":
          description: Datos inválidos
  /delete-user/{idCard}:
    get:
      tags:
        - admin
      summary: Eliminar un usuario
      description: Elimina un usuario por su ID de tarjeta
      operationId: deleteUser
      parameters:
        - name: idCard
          in: path
          required: true
          description: ID de tarjeta del usuario a eliminar
          schema:
            type: string
      responses:
        "200":
          description: Usuario eliminado
        "404":
          description: Usuario no encontrado
  /edit-user/{idCard}:
    get:
      tags:
        - admin
      summary: Editar un usuario
      description: Edita un usuario existente por su ID de tarjeta
      operationId: editUser
      parameters:
        - name: idCard
          in: path
          required: true
          description: ID de tarjeta del usuario a editar
          schema:
            type: string
      responses:
        "200":
          description: Datos del usuario
        "404":
          description: Usuario no encontrado
  /update-user:
    post:
      tags:
        - admin
      summary: Actualizar información de un usuario
      description: Actualiza la información de un usuario existente
      operationId: updateUser
      requestBody:
        description: Datos actualizados del usuario
        content:
          application/json:
            schema:
              type: object
              properties:
                idCard:
                  type: string
                name:
                  type: string
                email:
                  type: string
              required:
                - idCard
      responses:
        "200":
          description: Usuario actualizado
        "400":
          description: Datos inválidos
  /create-sector:
    post:
      tags:
        - sector
      summary: Crear un nuevo sector
      description: Crea un sector en el sistema
      operationId: createSector
      requestBody:
        description: Datos del sector a crear
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Sector creado
        "400":
          description: Datos inválidos
  /delete-sector/{id}:
    get:
      tags:
        - sector
      summary: Eliminar un sector
      description: Elimina un sector por su ID
      operationId: deleteSector
      parameters:
        - name: id
          in: path
          required: true
          description: ID del sector a eliminar
          schema:
            type: integer
      responses:
        "200":
          description: Sector eliminado
        "404":
          description: Sector no encontrado
  /edit-sector/{id}:
    get:
      tags:
        - sector
      summary: Editar un sector
      description: Edita un sector existente por su ID
      operationId: editSector
      parameters:
        - name: id
          in: path
          required: true
          description: ID del sector a editar
          schema:
            type: integer
      responses:
        "200":
          description: Datos del sector
        "404":
          description: Sector no encontrado
  /update-sector:
    post:
      tags:
        - sector
      summary: Actualizar un sector
      description: Actualiza la información de un sector existente
      operationId: updateSector
      requestBody:
        description: Datos actualizados del sector
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              required:
                - id
      responses:
        "200":
          description: Sector actualizado
        "400":
          description: Datos inválidos
  /create-interruption:
    post:
      tags:
        - interruption
      summary: Crear una interrupción
      description: Crea una interrupción en el sistema
      operationId: createInterruption
      requestBody:
        description: Datos de la interrupción a crear
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
              required:
                - description
      responses:
        "201":
          description: Interrupción creada
        "400":
          description: Datos inválidos
  /delete-interruption/{id}:
    get:
      tags:
        - interruption
      summary: Eliminar una interrupción
      description: Elimina una interrupción por su ID
      operationId: deleteInterruption
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la interrupción a eliminar
          schema:
            type: integer
      responses:
        "200":
          description: Interrupción eliminada
        "404":
          description: Interrupción no encontrada
  /edit-interruption/{id}:
    get:
      tags:
        - interruption
      summary: Editar una interrupción
      description: Edita una interrupción existente por su ID
      operationId: editInterruption
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la interrupción a editar
          schema:
            type: integer
      responses:
        "200":
          description: Datos de la interrupción
        "404":
          description: Interrupción no encontrada
  /update-interruption:
    post:
      tags:
        - interruption
      summary: Actualizar una interrupción
      description: Actualiza la información de una interrupción existente
      operationId: updateInterruption
      requestBody:
        description: Datos actualizados de la interrupción
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                description:
                  type: string
              required:
                - id
      responses:
        "200":
          description: Interrupción actualizada
        "400":
          description: Datos inválidos
  client/fetch-interruption:
    post:
      tags:
        - client
      summary: Obtener interrupciones por coordenadas
      description: Recupera las interrupciones basadas en las coordenadas proporcionadas.
      operationId: fetchInterruption
      requestBody:
        description: Coordenadas para buscar interrupciones.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coordinates:
                  type: string
                  description: |
                    Coordenadas separadas por coma (por ejemplo: 40.7128, -74.0060)
      responses:
        "200":
          description: Respuesta con las interrupciones encontradas.
          content:
            application/json:
              schema:
                type: object
                properties:
                  interruptions:
                    type: array
                    items:
                      type: object
                      properties:
                        startTime:
                          type: string
                          description: Hora de inicio de la interrupción en formato HH:MM.
                        endTime:
                          type: string
                          description: Hora de fin de la interrupción en formato HH:MM.
        "404":
          description: No se encontraron interrupciones para las coordenadas proporcionadas.
        "400":
          description: La solicitud no contiene coordenadas válidas.
        "500":
          description: Error del servidor al procesar la solicitud.
  client/dashboard:
    get:
      tags:
        - client
      summary: Obtiene el tablero del cliente
      description: Muestra el dashboard con las interrupciones del cliente.
      operationId: getDashboard
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Dashboard del cliente con interrupciones.
          content:
            text/html:
              schema:
                type: string
                example: "<html><body>Dashboard</body></html>"
        "401":
          description: No autenticado. El usuario debe estar autenticado para acceder a este recurso.
        "403":
          description: Correo electrónico no registrado. El usuario debe tener un correo electrónico registrado para acceder.

security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
